### ISSUE TITLE
How to translate this line?

### ISSUE THREAD

**Issue by ufechner7** [jverzani/SymPyPythonCall.jl#28]
How can I translate this line?
```
SymPy.PyCall.PyNULL()
```
I am trying to convert SymbolicControlSystems.jl to use this library.

**Comment by jverzani** [comment]
That should become

```
SymPyPythonCall.PythonCall.pynew()
```

(It is used to create a null object that is written to later in an `_init_` function.)

But, I'm in the middle of trying to consolidate the `SymPy` and `SymPyPythonCall` code bases into a package that I hope to begin registering today (`SymPyCore`). I don't expect any breakage, but if that package reaches into some internals, there may be. In the new case, you should be able to write `SymPyPythonCall._pynull()`

**Comment by ufechner7** [comment]
Thank you!
