### ISSUE TITLE
workflow after separating out Core package

### ISSUE THREAD

**Issue by thorek1** [jverzani/SymPyPythonCall.jl#35]
when updating to the latest SymPyPythonCall unSym (and many other functions) are no longer exported. I am not sure if this is a feature and we are supposed to import the core package as well or a bug :) I would advocate for exporting the functions from the PythonCall and PyCall packages and leave the Core package invisible to the user.

**Comment by jverzani** [comment]
Thanks. that was bad form. I'll put in proper deprecations in the next release, hopefully today. (For now, unSym is just the unicode \downarrow[tab].)

**Comment by jverzani** [comment]
CLosed in #36. Please reopen if that didn't address the issue.
