### ISSUE TITLE
register SymPyCall

### ISSUE THREAD

**Issue by thorek1** [jverzani/SymPyPythonCall.jl#9]
any chance of registering the package? 

It solves a major headache of mine (automatic sympy install via CondaPkg). Manual sympy install is a major entrance hurdle for less tech savvy users.

I tested it in my package as a backend for sympy instead of SymPy.jl and it works on the test cases.

**Comment by jverzani** [comment]
Sure, I'll try and get to this soon.

But isn't `SymPy.jl` easier to install. I haven't looked here in a bit, but it seems you have to type a few commands to install SymPy.

**Comment by thorek1** [comment]
The issue is `SymPy.jl` doesn't take care of the `sympy` python package installation for you, because it relies on `PyCall.jl` and `Conda.jl`. 

`SymPyCall.jl` does install the `sympy` python package automatically thanks to `PythonCall.jl` and `CondaPkg.jl`. 

The drawback of having `PythonCall.jl` as a backend is that you cannot (snoop-)precompile anything involving python.

Since I rely on `sympy` for my package I want this part to be as easy as possible (automatic installation via `CondaPkg.jl`).

**Comment by jverzani** [comment]
Okay, I'm running tests now to see if anything needs updating beyond replacing `getpy` with `Py`. I get an error about not finding sympy, so I need to do something to adjust for the different packaging.

**Comment by thorek1** [comment]
I went down that route as well and replacing getpy with Py was enough to use the latest PythonCall. I didn't look into Markdown or Latexify and the respective files though.

**Comment by jverzani** [comment]
Yeah, surprisingly it mostly works. I'm bumping into an issue with calling methods of a symbolic matrix. But hopefully, nothing deal breaking. (I just have to remember how to use PythonCall...)

**Comment by jverzani** [comment]
Closed in #10. WIll initiate registration next.

**Comment by jverzani** [comment]
This just got registered, though with a bit of a different name: `SymPyPythonCall`. Maybe the first example in the docs should be `const SymPy = SymPyPythonCall`....

Thanks for the suggestion.
